a, b, c = input().split()
TRIANGULO = 0.5 * float(a) * float(c)
CIRCULO = 3.14159 * float(c) * float(c)
TRAPEZIO = 0.5 * (float(a) + float(b)) * float(c)
QUADRADO = float(b) * float(b)
RETANGULO = float(a) * float(b)
print("TRIANGULO: {0:.3f}".format(TRIANGULO))
print("CIRCULO: {0:.3f}".format(CIRCULO))
print("TRAPEZIO: {0:.3f}".format(TRAPEZIO))
print("QUADRADO: {0:.3f}".format(QUADRADO))
print("RETANGULO: {0:.3f}".format(RETANGULO))
